FROM golang:1.24.3-alpine

# Установка Chrome и всех необходимых зависимостей
RUN apk add --no-cache \
    chromium \
    chromium-chromedriver \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    udev \
    xvfb \
    dbus

# Установка переменных окружения
ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/ \
    CHROMEDP_NO_SANDBOX=true \
    CHROMEDP_DISABLE_GPU=true \
    DISPLAY=:99

WORKDIR /app/search_service

# Копируем и собираем приложение
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o search_service .

EXPOSE 8081

# Запускаем Xvfb перед основным приложением
CMD Xvfb :99 & ./search_service